[package]
name = "discordTool-CLI"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = { version = "0.11", default-features = false, features = ["gateway", "model", "client", "rustls_backend"] }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
rustls = "0.20" 

